from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import Optional
from services.stock_service import get_stock_data
from services.forecasting import forecast_stock
from services.anomaly_detection import detect_stock_anomalies
from services.ai_service import generate_insight
from models.user import User
from core.dependencies import get_current_user
from datetime import datetime

router = APIRouter(prefix="/api/reports", tags=["reports"])

class ReportRequest(BaseModel):
    type: str = "stock"
    id: str = "AAPL"
    include_forecast: bool = True

@router.post("/generate")
async def generate_report(req: ReportRequest, current_user: User = Depends(get_current_user)):
    if req.type == "stock":
        symbol = req.id.upper()
        stock_data = await get_stock_data(symbol, period="1y")
        if "error" in stock_data:
            raise HTTPException(status_code=404, detail=stock_data["error"])

        anomalies_result = detect_stock_anomalies(stock_data["data"])
        forecast_result: dict = {}
        if req.include_forecast:
            fr = forecast_stock(stock_data["data"], horizon=30)
            if "error" not in fr:
                forecast_result = fr

        prices = [d["close"] for d in stock_data["data"]]
        if len(prices) > 1 and prices[0] != 0:
            price_change = round(((prices[-1] - prices[0]) / prices[0]) * 100, 2)
        else:
            price_change = 0

        ai_summary = generate_insight(
            f"Stock: {symbol}, Price change: {price_change}%, Anomalies: {anomalies_result.get('total', 0)}",
            f"Generate a brief professional report summary for {symbol}"
        )

        return {
            "id": f"report_{symbol}_{datetime.now().strftime('%Y%m%d%H%M%S')}",
            "type": "stock",
            "symbol": symbol,
            "generated_at": datetime.now().isoformat(),
            "summary": {
                "current_price": stock_data["current_price"],
                "price_change_1y": price_change,
                "anomalies_count": anomalies_result.get("total", 0),
                "trend": forecast_result.get("trend", "unknown"),
                "confidence": forecast_result.get("confidence", 0),
            },
            "findings": [
                f"Price trend: {'+' if price_change > 0 else ''}{price_change}% over the analyzed period",
                f"{anomalies_result.get('total', 0)} significant anomalies detected",
                f"Current price: ${stock_data['current_price']}",
                f"52W High: ${stock_data['high_52w']}, 52W Low: ${stock_data['low_52w']}",
                f"Forecast trend: {forecast_result.get('trend', 'N/A').capitalize() if forecast_result else 'N/A'}",
            ],
            "ai_summary": ai_summary,
            "chart_data": stock_data["data"][-30:],
            "forecast": forecast_result.get("forecast", [])[:10] if forecast_result else [],
        }
    raise HTTPException(status_code=400, detail="Invalid report type")

@router.get("/{report_id}/export/json")
def export_json(report_id: str, current_user: User = Depends(get_current_user)):
    return {"report_id": report_id, "format": "json", "message": "JSON export - implement with stored report data"}

@router.get("/{report_id}/export/markdown")
def export_markdown(report_id: str, current_user: User = Depends(get_current_user)):
    md = f"# Analysis Report\n\nReport ID: {report_id}\n\nGenerated by Auto Data Scientist"
    return {"content": md, "format": "markdown"}
